### ISSUE TITLE
Mailchimp  API 2.0 Deprecated

### ISSUE THREAD

**Issue by ibarrajo** [gomfunkel/node-mailchimp#43]
New API documentation:
http://kb.mailchimp.com/api/

Old API and announcement on the 2.0 deprecation.
https://apidocs.mailchimp.com/

**Comment by PEM--** [comment]
Are you planning on integrating 3.0 API?

**Comment by wulfsolter** [comment]
Would love to, but it's not currently in my immediate plans as v2 is still working for us... Would welcome a PR? It should be pretty straightforward ;)
