### ISSUE TITLE
Library not handling Gzip compression, breaking response

### ISSUE THREAD

**Issue by philhudson91** [gomfunkel/node-mailchimp#46]
http://stackoverflow.com/questions/33992930/error-error-parsing-json-answer-from-mailchimp-api

Getting an error from the NodeJS MailChimp - using:

https://github.com/gomfunkel/node-mailchimp

Error: Error parsing JSON answer from MailChimp API: �V*.I,)-V�RJ-*�/R�QJ�OIU�220�Q�K�2�|2�K�]�S���K\+��*�j+%ϼ�Ĝ���������jO+SKK�Z��T��c
I do not understand why this is happening, my calls are pretty vanilla, see below:

var MailChimpAPI = require('mailchimp').MailChimpAPI,
    apiKey = 'asaas',
    mainListId = 45949;

try {
    var api = new MailChimpAPI(apiKey, {version: '2.0'});
} catch (error) {
    console.log(error.message);
}

var options = {
    id: mainListId, //12345
    email: {
        email: email //validemail@email.com
    },
    double_optin: false,
    send_welcome: false
};

console.log(options);

api.call('lists', 'subscribe', options, function (error, data) {
    if (error) {
        console.log(error.message);
        callback(error, null);
    } else {
        console.log(JSON.stringify(data)); // Do something with your data!
        callback(null, data);
    }
});

**Comment by wulfsolter** [comment]
This library is really just a pretty wrapper around https://github.com/request/request as you can see here https://github.com/gomfunkel/node-mailchimp/blob/master/lib/mailchimp/MailChimpAPI_v2_0.js#L52

Do you think the request/gzip issue could be linked to https://github.com/request/request/issues/1680 ? I'm currently not actively using this lib in production, but could you try augmenting the MailChimpAPI_v2_0.prototype.execute function linked above with a `'gzip:true,'` and seeing if that resolves the issue?

**Comment by Magiweb** [comment]
Modified request object to include gzip in node_modules/mailchimp/lib/mailchimp/MailChimpAPI_v2_0.js line 52:

 request({
  uri : this.httpUri+'/'+this.version+'/'+method,
  method: 'POST',
  headers : { 'User-Agent' : this.userAgent+'node-mailchimp/'+this.packageInfo.version, "accept-encoding" : "gzip,deflate"},
  gzip: true,
  body : JSON.stringify(finalParams)
 }, function (error, response, body) {
  helpers.handleMailChimpResponse(error, response, body, callback);
 });

Now works flawlessly for both gzip-encoded and normal requests. @gomfunkel could you please update? Already tested and working - just copy/paste please :)

**Comment by wulfsolter** [comment]
@Magiweb: So exactly what I wrote earlier? Thank you for verifying.

If you could submit a PR I will merge.

**Comment by wulfsolter** [comment]
@Magiweb Glad to see it works. Mind submitting a PR?

**Comment by Magiweb** [comment]
@wulfsolter pull request submitted :)
