### ISSUE TITLE
The API method lists_batch_subscribe does not exist

### ISSUE THREAD

**Issue by slavafomin** [gomfunkel/node-mailchimp#47]
Hello!

I'm making a call to API 2.0 using the following code:

```javascript
var mailChimpApi = new MailChimpAPI(
  parameters.mailing.mailchimpKey, {
    version : '2.0'
  }
);
mailChimpApi.call('lists', 'batch-subscribe', {
  id: list.listId,
  batch: subscribeBatch,
  double_optin: false,
  update_existing: true
}, function () { /** ... */ });
```

Method description: https://apidocs.mailchimp.com/api/2.0/lists/batch-subscribe.php

I'm getting the following error: `The API method lists_batch_subscribe does not exist`.

Please advise! Thank you!

**Comment by jeffreypriebe** [comment]
@slavafomin Did you get this to work?
Looks like the method is there both in the apidocs (your link) and in the [source](https://github.com/gomfunkel/node-mailchimp/blob/master/lib/mailchimp/MailChimpAPI_v2_0.js#L568)
Did you notice the API Key restriction on the MailChimp API doc: needs to be an API key of particular level.

**Comment by slavafomin** [comment]
Hey! Try `batchSubscribe` instead of `batch-subscribe`.

**Comment by jeffreypriebe** [comment]
@slavafomin Thanks. So this is a solved issue? Great!
cc @wulfsolter

**Comment by wulfsolter** [comment]
Thanks @jeffreypriebe :)
