### ISSUE TITLE
API v3.0 support

### ISSUE THREAD

**Issue by Dids** [gomfunkel/node-mailchimp#54]
Any plans for adding this? I see that v2.0 will be unsupported after 2016, so adding support for it is probably a good idea at this point, unless of course it already supports it.

**Comment by MiroHibler** [comment]
@Dids, see #45 and #49 ;)

**Comment by Dids** [comment]
Ah, well darn. Not sure if this should be kept open as a reminder or not. :P

**Comment by MiroHibler** [comment]
My thoughts exactly. :P

**Comment by wulfsolter** [comment]
I'm hoping someone will do a PR before Mailchimp deprecates 2.x API... ;) It's on my list of things to do, but a few hundred hours of tasks from the top.

**Comment by faceyspacey** [comment]
doesn't sound like there's enough remaining time in 2016  ;) ...maybe a document describing what needs to be done might help inspire those not familiar with the inner-workings of the package.

**Comment by josiahsprague** [comment]
It looks like @sumitkumar1209 may have started a fork with API v3.0 support. Sumit, what's the status of [your fork](https://github.com/sumitkumar1209/node-mailchimp)? Can it be used to connect with MailChimp API v3.0? If so, what else needs done before a PR can be opened from your fork into the main repo? Is there anything we could do to help?

**Comment by josiahsprague** [comment]
For those looking for an easy way to connect with MailChimp API v3.0, check out https://github.com/thorning/node-mailchimp

**Comment by sumitkumar1209** [comment]
@josiahsprague My fork is simple http wrapper on MailChimp http API. I am not able to get enough time to document that, so I haven't created a pull request yet.

**Comment by masonlouchart** [comment]
I guess this issue could be closed. Like @localjo said, [there is another repo for the v3](https://github.com/thorning/node-mailchimp).
